name: Color Picker
description: Custom Color Picker
version: 1.0.0
author: Ta-Yi Cheng <admin@tranquility.tech>
homepage: https://github.com/TranquilityTech/FlutterColorPicker

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
